[workspace]
members = [
  "intouch2",
  "intouch2-mqtt",
]

[profile.release]
codegen-units = 1
lto = true
strip = true

[patch.crates-io]
disjoint_impls = { git = "https://github.com/Ofenhed/disjoint_impls.git" }
