name: "Intouch2-MQTT"
description: "A bridge between intouch2, used in spa systems, and MQTT 3.3"
version: "0.1.63"
slug: "intouch2-mqtt"
init: false
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
stage: experimental
services:
  - "mqtt:want"
ingress: false
schema:
  spa:
    target: str
    unique_id: str
    memory_size: int(1,65535)
    udp_timeout: int(1,600)?
    forward:
      custom_value: true
      multiple: true
    handshake_timeout: int(1,60)?
  verbose: bool?
  dump_traffic: bool?
  memory_changes_topic: str?
  mqtt:
    target: str?
    discovery_topic: str?
    auth:
      custom_value: true
      multiple: true
