name: "Intouch2-MQTT"
description: "A bridge between intouch2, used in spa systems, and MQTT 3.3"
version: "0.1.6"
slug: "intouch2-mqtt"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
host_network: true
stage: experimental
schema:
  spa_target: str
  spa_name: str
  forward_port: int(1,65535)?
  forward_listen_ip: str?
  spa_memory_size: int(1,65535)
  mqtt_target: str?
  mqtt_username: str?
  mqtt_password: password?
  home_assistant_discovery_topic: str?
  udp_timeout: int(1,600)?
  handshake_timeout: int(1,60)?
