name: "Intouch2-MQTT"
description: "A bridge between intouch2, used in spa systems, and MQTT 3.3"
version: "0.1.73"
slug: "intouch2-mqtt"
init: false
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
stage: experimental
services:
  - "mqtt:want"
ingress: false
schema:
  spa_target: str
  spa_id: str
  spa_memory_size: int(1,65535)
  spa_udp_timeout: int(1,600)?
  spa_handshake_timeout: int(1,60)?
  verbose: bool?
  dump_traffic: bool?
  memory_changes_mqtt_topic: str?
  mqtt_target: str?
  mqtt_username: str?
  mqtt_password: password?
  mqtt_discovery_topic: str?
  lights_json:
    - str

  pumps_json:
    - str
