# Activation of features, almost objectively better ;)
use_try_shorthand = true
use_field_init_shorthand = true
condense_wildcard_suffixes = true
normalize_comments = true
wrap_comments = true
imports_granularity = "Crate"
tab_spaces = 2

# Heavily subjective style choices
comment_width = 100
