[package]
name = "intouch2-mqtt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.34", features = ["macros", "rt-multi-thread"] }
intouch2 = { path = "../intouch2" }
palette = "0.6"
clap = { version = "4.4", features = ["derive", "env"] }
rand = "0.8"
serde = { version = "1.0", features = ["rc"] }
serde_json = "1.0"
reqwest = { version = "0.11", default-features = false, features = ["tokio-rustls", "rustls-tls"] }
strum = { version = "0.25", features = ["derive"] }
mqttrs = { version = "0.4.1", features = ["derive"] }
thiserror = "1.0"
anyhow = "1.0"
